### ISSUE TITLE
Terraform v0.12 - iam-dynamic-group - Error: Incorrect attribute value type

### ISSUE THREAD

**Issue by shmiyazima** [oracle-terraform-modules/terraform-oci-iam#11]
--------------------------------------------------------------------------------------------------
Error: Incorrect attribute value type

on ../modules/iam-dynamic-group/main.tf line 37, in resource "oci_identity_policy" "this":
37: statements = ["${var.policy_statements}"]

Inappropriate value for attribute "statements": element 0: string required.
--------------------------------------------------------------------------------------------------
Fix:
File: ../modules/iam-dynamic-group/main.tf line 37

line 37 - update
Command: statements = ["${var.policy_statements}"]
To: statements = var.policy_statements

**Comment by kral2** [comment]
this issue is resolved by PR #13
