### ISSUE TITLE
Terraform v012.0 - iam-group - Error: Incorrect attribute value type

### ISSUE THREAD

**Issue by shmiyazima** [oracle-terraform-modules/terraform-oci-iam#12]
--------------------------------------------------------------------------------------------------
Error: Incorrect attribute value type

on ../modules/iam-group/main.tf line 50, in resource "oci_identity_policy" "this":
50: statements = ["${var.policy_statements}"]

Inappropriate value for attribute "statements": element 0: string required.
--------------------------------------------------------------------------------------------------
Fix:
File: ../modules/iam-group/main.tf line 50

line 50 - update
Command: statements = ["${var.policy_statements}"]
To: statements = var.policy_statements

**Comment by kral2** [comment]
Hello,
This bug is resolved by PR #13
