### ISSUE TITLE
"deprecated" Warnings with TF v0.12.21

### ISSUE THREAD

**Issue by shinystar93** [oracle-terraform-modules/terraform-oci-iam#16]
I use module iam-group and iam-user and receive many "deprecated" Warnings with TF v0.12.21. This should be fixed.

Warning #1 
> Warning: Interpolation-only expressions are deprecated
>   on .terraform/modules/iam_group/terraform-oci-iam-1.0.3/modules/iam-group/main.tf line 7, in resource "oci_identity_group" "this":
>    7:   count          = "${var.group_create ? 1 : 0}"
> Terraform 0.11 and earlier required all non-constant expressions to be
> provided via interpolation syntax, but this pattern is now deprecated. To
> silence this warning, remove the "${ sequence from the start and the }"
> sequence from the end of this expression, leaving just the inner expression.

Warning #2 
> Warning: Quoted references are deprecated
>   on .terraform/modules/iam_group/terraform-oci-iam-1.0.3/modules/iam-group/main.tf line 46, in resource "oci_identity_policy" "this":
>   46:   depends_on     = ["oci_identity_group.this"]
> In this context, references are expected literally rather than in quotes.
> Terraform 0.11 and earlier required quotes, but quoted references are now
> deprecated and will be removed in a future version of Terraform. Remove the
> quotes surrounding this reference to silence this warning.

I attach the modified files for reference.
[iam-user_main.tf.txt](https://github.com/oracle-terraform-modules/terraform-oci-iam/files/4789117/iam-user_main.tf.txt)

[iam-group_main.tf.txt](https://github.com/oracle-terraform-modules/terraform-oci-iam/files/4789132/iam-group_main.tf.txt)

**Comment by shinystar93** [comment]
btw - is this a living project or is it a dead horse ? Issues don't get closed and the last modifications happened more than a year ago ... who is in charge ? Should I open a new branch with the fixes ? And create a merge request ?

**Comment by kral2** [comment]
Hello @shinystar93 

This is a living project. We are in the process to fix all 0.12 compatibility issues (see PR #13).
As soon as we get these changes merged, I will try to reflect the actual status to all the related issues.

I would not advise to fork/PR for changes related to 0.12 compatibility, as they are already addressed in PR #13.
But any future contribution is welcome and would be evaluated for code merge.
