### ISSUE TITLE
examples are calling for the module version 2.1.1, but only the 2.0.0 is available in the registry

### ISSUE THREAD

**Issue by aorcl** [oracle-terraform-modules/terraform-oci-iam#18]
```
$ terraform init
Initializing modules...

Error: Unresolvable module version constraint

There is no available version of module
"oracle-terraform-modules/iam/oci//modules/iam-compartment" (main.tf:41) which
matches the given version constraint. The newest available version is 2.0.0.
...
```

**Comment by kral2** [comment]
Idem pour ces exemples. Ils sont tous revus, j’attends de terminer un point pour les pousser.

Le 2.1.1 vient dur faut que sur mon fork, j’ai accumulé les tags et on étaient « loin ».

Sur l’officiel, j’ai squash/merge histoire de ne pas exposer inutilement les 13 commit de la PR, et du coup j’en ai profité pour tout passer en 2.0.0 : j’ai loupé des points dans la doc ...

Pour une raison inexpliquée, je me rend compte des PB que lorsque la page est sur GitHub 🤪

Je vais essayer de mettre en place un truc pour ne plus avoir ce pb: y’a trop de code dans différentes pages géré manuellement. C’est case-gueulle, facile d’en oublier un morceau lors d’une MAJ.

Note: vendredi j’ai bossé sûre bouton « deploy to oracle cloud », ça marche plutôt bien 🤩 -> je vais introduire ça dans les sections examples.

Çetin,

+336 2881 0573
cetin.ardal@gmail.com

Envoyé de mon iPhone
