### ISSUE TITLE
Error: Duplicate required providers configuration  both on (versions.tf and main.tf) . A module may have only one required providers configuration 

### ISSUE THREAD

**Issue by brokedba** [oracle-terraform-modules/terraform-oci-iam#33]
I'm using Terraform v1.0.3 and the modules aren't compatible with a change that appeared in 0.13 already 
>We now permit at most one required_providers block per module (except for overrides). This prevents users (and Terraform) from struggling to understand how to merge multiple required_providers configurations, with version and source attributes split across multiple blocks.

This is a purposeful change for 0.13. see terraform #issue https://github.com/hashicorp/terraform/issues/25364

you have to make your mind now either keep required_provider clause in version.tf or in the main otherwise this module is useless.
````
Initializing modules...
Downloading oracle-terraform-modules/iam/oci 2.0.2 for iam_compartment_x...
- iam_compartment_x in .terraform/modules/iam_compartment_x/modules/iam-compartment
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Duplicate required providers configuration
│
│   on .terraform/modules/iam_compartment_x/modules/iam-compartment/versions.tf line 2, in terraform:
│    2:   required_providers {
│
│ A module may have only one required providers configuration. The required providers were previously configured at .terraform/modules/iam_compartment_x/modules/iam-compartment/main.tf:5,3-21.
```

**Comment by atalakey4work** [comment]
Any update on getting this fixed?

**Comment by brokedba** [comment]
> Any update on getting this fixed?
@atalakey4work If you just want to use the compartment module , I have a clean/corrected version in my repo that you can use locally .
see folder >> https://github.com/brokedba/terraform-examples/tree/master/terraform-provider-oci/compartments/modules/iam-compartment

**Comment by ahmedmansour5** [comment]
@brokedba Thanks, your updated version did the trick!
