### ISSUE TITLE
Document string format for dynamic group matching rule when there are more than one

### ISSUE THREAD

**Issue by craig-silva** [oracle-terraform-modules/terraform-oci-iam#40]
I am a bit constrained in accessing the dev tenancy we are developing.

So I was looking for some guidance in the documentation on how to add multiple matching rules for dynamic groups.

Are the rules separated by commas or newlines - I'm trying to use the heredoc form, which passes terraform plan, but fails on apply.

**Comment by robo-cap** [comment]
The matching rule for a dynamic group when you want to use multiple matching criteria can be something like this:

`any {all {resource.type='datasciencenotebooksession', resource.compartment.id='<your_compartment_ocid>'}, all {resource.type='datasciencemodeldeployment',resource.compartment.id='<your_compartment_ocid>'}, all {resource.type='datasciencejobrun', resource.compartment.id='<your_compartment_ocid>'}}`

If you are looking for something simple you can use:
`all {resource.type='datasciencenotebooksession', resource.compartment.id='<your_compartment_ocid>'}`

Dynamic group documentation: https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingdynamicgroups.htm

**Comment by craig-silva** [comment]
Thank you - magic key was any { any{....}, all{....}} - I was missing the first any>

I could say that it might help others if a specific example of multiple matching rules could be provided in docs
